[tasks.clean]
description = "Clean proyect"
command = "cargo"
args = ["clean"]


[tasks.build]
command = "cargo"
args = ["build"]



[tasks.test]
command = "cargo"
args = ["test"]


[tasks.run]
command = "cargo"
args = ["run"]

[tasks.doc]
command = "cargo"
args = ["doc","--document-private-items"]

[tasks.release]
command = "cargo"
args = ["build", "--release", "--bin", "CloudBanking"]

[tasks.doccopy]
script = [
    "echo $PWD",
    "cp -rf target/doc/ docs/documentation" 
]
dependencies = ["clean"]


[tasks.dirtree]
script = [
    "find Gemfile README.md cc.yaml  make.toml LICENSE _config.yml src install makefile .github/workflows .gitignore .travis.yml  -type f |  cut -d/ -f-4 | uniq  |  dirtree -o docs/dirtree.html"
]
