# This is a basic workflow to help you get started with Actions

name: "Check cc.yaml file"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "cc.yaml"

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v2.0.0
        with:
          file_or_dir: "cc.yaml"
          
      - name: Check -entidad- existence
        id: counter-entidad
        # If grep | wc -l != 0 -> Exist this word in file, 
        run: echo ::set-output name=entidad::$(grep "entidad" cc.yaml | wc -l)
        shell: bash
        if: steps.counter-entidad.entidad == '1'
